name: Go CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
      - name: Check formatting
        run: |
          fmt_files=$(gofmt -l .)
          if [ -n "$fmt_files" ]; then
            echo "The following files are not properly formatted:" >&2
            echo "$fmt_files" >&2
            gofmt -d $fmt_files >&2
            exit 1
          fi
      - name: Test
        run: go test ./...
